# Generated by Django 4.1.7 on 2023-03-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='rollno',
            field=models.IntegerField(null=True),
        ),
    ]
